### ISSUE TITLE
Not working on meteor 2.0

### ISSUE THREAD

**Issue by gilshallem** [VladShcherbin/meteor-user-permissions#1]
![image](https://user-images.githubusercontent.com/8035623/144026922-32292272-7b1f-4698-888c-bf6a015ccb90.png)

Giving this error right after i add this plugin to the project

**Comment by vladshcherbin** [comment]
This project is 6 years old and has no Meteor 2 support. Better search for another package 😉

**Comment by gilshallem** [comment]
Too bad I relly like the simplicity of this one :) thank you
